# Generated by Django 4.1.7 on 2023-03-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Famale'), (3, 'Other')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrator'), (2, 'Caregiver'), (3, 'BabySitter'), (4, 'Client')], default='1'),
            preserve_default=False,
        ),
    ]
